server:
  port: 8082

spring:
  application:
    name: registration-service
  

  datasource:
    url: jdbc:mysql://localhost:3306/regdb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""   

  

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        #type:
          #enum_as_string: true

jwt:
  secret: 2XZCFpmx0gac8Obn7LVsXtxpT36eCKVBGEbXg3luFuN2
  expiration: 720000

app:
  event-service-url: http://localhost:8081
  notification-service-url: http://localhost:8083
  authenification-service-url : http://localhost:8080



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true   